services:
  backend:
    image: newnowregistry.azurecr.io/hpe-backend:latest
    # Backend only exposed internally, not to the internet
    expose:
      - "8000"
    environment:
      - PYTHONUNBUFFERED=1
      - ALLOWED_ORIGINS=https://hpe-smart-choice.azurewebsites.net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - app-network

  frontend:
    image: newnowregistry.azurecr.io/hpe-frontend:latest
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
