services:
  backend:
    image: newnowregistry.azurecr.io/hpe-backend:latest
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - app-network

  frontend:
    image: newnowregistry.azurecr.io/hpe-frontend:latest
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - app-network
    environment:
      - VITE_API_URL=http://backend:8000

networks:
  app-network:
    driver: bridge
